language: java
jdk:
  - oraclejdk8

env:
  global:
    - ORG_GRADLE_PROJECT_INTELLIJ_DOWNLOAD_SOURCES=false
  matrix:
    - ORG_GRADLE_PROJECT_INTELLIJ_VERSION=2016.1
    - ORG_GRADLE_PROJECT_INTELLIJ_VERSION=LATEST-EAP-SNAPSHOT

matrix:
  fast_finish: true
  allow_failures:
    - env: ORG_GRADLE_PROJECT_INTELLIJ_VERSION=LATEST-EAP-SNAPSHOT

before_deploy:
  - ./gradlew buildPlugin
  - if [[ $ORG_GRADLE_PROJECT_INTELLIJ_VERSION = 2016.1 ]]; then ./gradlew publishPlugin; fi

deploy:
  provider: releases
  api_key:
    secure: WRn4wcXvWYWIUzlxjo1xpESOhSnMp9fPOfnwye2KQOogbCGFUwmqzeSvQFxaOMvaIXvAZka1HUFjgj+9tPSfpuXp9FGFupTH8IWooJuro9ool4IJYpJBCwbKU5oDk0vnRizBXGQiDa1jdkQpn35ufWupsLzofawzyFnJ5DmUhqp7fBqXLZzK29gBPaIhMDDXEvqGPKweIYQuzBRztOo2pFwoSYSMhZUSVxkChmFxsFTUuUXKM0Lzy1l93ky6vHYs3rLcWx4yOFGGzIQXUH3jQxItz0oWx9CyA786JderA9mFbK6B48aYAyAfcI6qgK3mxFMiX1wHpgBzYpHe/aT/Rps4hhkUCtsQVrL8DR3Lv1DDzEPvmRFMdxs1+gw2/AiZkBeZYQ0kP++dn6xUThy6UkyRXloqInLDREw7AYeNR+ORwLAYTNLGhrp7HUb8woP8g3O/yKRkaHtqAWNidqMJXobCMfyOjDz38PaGtLfXgs0h8QTnH7113d1VQi4fFhFyp+968XNthvh6EncT50kJjjUZY5aM8SOt5cXCvho1ScDjNB7IEkzgaYrC5QepwQi4y+4+N99FVH/4pVjPft2ncl7pddrIgoSkzXiKGDe1Z2lc4z4e/WegiIgXH23w/NANJRMnuPB9p5knOxIp2fhNFOVkGyTVLu2ehchSqzK+FD4=
  file_glob: true
  file: build/distributions/Ember.js-*.zip
  on:
    repo: Turbo87/intellij-emberjs
    tags: true
