version: "{branch} {build}"

environment:
  global:
    ORG_GRADLE_PROJECT_INTELLIJ_DOWNLOAD_SOURCES: false

install:
  - git submodule update --init --recursive

build_script:
  - gradlew.bat assemble

test_script:
  - gradlew.bat check
